FROM node:10-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY ./dist-nodejs/*.js* ./

USER node

COPY --chown=node:node . .

EXPOSE 30100

CMD [ "node", "index.js" ]