name: 'Build Docker image for GitHub (Golang)'

on:
  workflow_dispatch:

jobs:
  build:
    uses: actiwaredevelopment/action-io-build-workflows/.github/workflows/build-golang-io-module.yml@main
    with:
      repository: ${{ github.repository }}
      version-postfix: '-developer'
      branch: ${{ github.ref_name }}
      mainfile: src/service-v2-go/cmd/service/main.go
      outputfile: io-module-service
      modulefile: template.zip
      dockerfile: ./.github/docker/dockerfile-go
      go-os: 'linux'
      go-arch: 'amd64'
    secrets:
      action-user: ${{ secrets.GH_ACTION_USER }}
      action-token: ${{ secrets.GH_ACTION_TOKEN }}
      awdev-nuget-source: ${{ secrets.AWDEV_NUGET_URL }}
      npm-package-token: ${{ secrets.AWDEV_NPM_PACKAGE_TOKEN }}
      npmrc-config: ${{ secrets.NPMRC_CONFIG }}

  docker:
    needs: [build]

    uses: actiwaredevelopment/action-io-build-workflows/.github/workflows/publish-to-github-docker.yml@main
    with:
      artifact: ${{ needs.build.outputs.download }}
      image-name: io2-module-template
      image-tag: developer
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}