name: 'Nightly Build (Auto)'

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-last-commits:
    name: Check Repository
    uses: actiwaredevelopment/action-io-repo-last-commit-check/.github/workflows/check-repository.yml@main
    with:
      repository: ${{ github.repository }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    if: ${{ needs.check-last-commit.outputs.has-changes == 'true' }}
    needs: check-last-commits

    uses: actiwaredevelopment/action-io-build-workflows/.github/workflows/build-dotnet-io-module.yml@main
    with:
      repository: ${{ github.repository }}
      version-postfix: '-nightly'
      branch: ${{ github.ref_name }}
      dotnet-version: 6.0.x
      project: src/service-v2-dotnet/service/io2-module-template-service.csproj
      modulefile: template.zip
      dockerfile: ./.github/docker/dockerfile
      ui-build-path: ./src/configuration/build
      rid: 'linux-x64'
      create-single-file: false
    secrets:
      action-user: ${{ secrets.GH_ACTION_USER }}
      action-token: ${{ secrets.GH_ACTION_TOKEN }}
      awdev-nuget-source: ${{ secrets.AWDEV_NUGET_URL }}
      npm-package-token: ${{ secrets.AWDEV_NPM_PACKAGE_TOKEN }}
      npmrc-config: ${{ secrets.NPMRC_CONFIG }}

  docker:
    if: ${{ needs.check-last-commit.outputs.has-changes == 'true' }} 
    needs: [check-last-commits, build]

    uses: actiwaredevelopment/action-io-build-workflows/.github/workflows/publish-to-docker.yml@main
    with:
      artifact: ${{ needs.build.outputs.download }}
      image-name: actiwareio/io-module-template
      image-tag: nightly
    secrets:
      docker-username: ${{ secrets.DOCKER_HUB_USER }}
      docker-password: ${{ secrets.DOCKER_HUB_SECRET }}
