name: 'Build Docker image for GitHub (Nodejs)'

on:
    workflow_dispatch:

jobs:
    build:
        uses: actiwaredevelopment/action-io-build-workflows/.github/workflows/build-nodejs-io-module.yml@main
        with:
            repository: ${{ github.repository }}
            version-postfix: '-developer'
            branch: ${{ github.ref_name }}
            project: ./src/service-v2-nodejs
            modulefile: iotemplate.zip
            dockerfile: ./.github/docker/dockerfile-nodejs
            build-path: ./dist-nodejs
        secrets:
            action-user: ${{ secrets.GH_ACTION_USER }}
            action-token: ${{ secrets.GH_ACTION_TOKEN }}
            awdev-nuget-source: ${{ secrets.AWDEV_NUGET_URL }}
            npm-package-token: ${{ secrets.AWDEV_NPM_PACKAGE_TOKEN }}
            npmrc-config: ${{ secrets.NPMRC_CONFIG }}

    docker:
        needs: [build]

        uses: actiwaredevelopment/action-io-build-workflows/.github/workflows/publish-to-github-docker.yml@main
        with:
            artifact: ${{ needs.build.outputs.download }}
            image-name: io2-module-iotemplate
            image-tag: developer
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
